### ISSUE TITLE
Get `$id` without context

### ISSUE THREAD

**Issue by Medformatik** [lohanidamodar/flappwrite_account_kit#12]
Is there a way to get the `$id` of the current user in `initState`, since I can't use `context` there?

Here is an example:
```dart
@override
void initState() {
    super.initState();
    boatsStream = DB.boat.streamBoats(uid); // Initialize the stream
}
```
I somehow need to get the users id here. But it's not only `initState` functions where I need to get the `$id` without `context`, for example in the `toMap` function of some of my models I also need it.

**Comment by Medformatik** [comment]
For the example above I can just move the initialization to the `build` method, but e.g. in my models there is no way of getting the `context`.

**Comment by lohanidamodar** [comment]
You need to refactor you code to use it other way. It works with context because we do need context to access the state data. As we are using the inherited widget, we need context to access the data. You can easily refactor your code to pass context. 
For initState you could move your logic to `didChangeDependencies` (https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html)
